<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['name'=> 'ARICA','code' =>'15101','state_code' => '15']);
        City::create(['name'=> 'CAMARONES','code' =>'15102','state_code' => '15']);
        City::create(['name'=> 'PUTRE','code' =>'15201','state_code' => '15']);
        City::create(['name'=> 'GENERAL LAGOS','code' =>'15202','state_code' => '15']);
        City::create(['name'=> 'IQUIQUE','code' =>'01101','state_code' => '01']);
        City::create(['name'=> 'ALTO HOSPICIO','code' =>'01107','state_code' => '01']);
        City::create(['name'=> 'POZO ALMONTE','code' =>'01401','state_code' => '01']);
        City::create(['name'=> 'CAMIÑA','code' =>'01402','state_code' => '01']);
        City::create(['name'=> 'COLCHANE','code' =>'01403','state_code' => '01']);
        City::create(['name'=> 'HUARA','code' =>'01404','state_code' => '01']);
        City::create(['name'=> 'PICA','code' =>'01405','state_code' => '01']);
        City::create(['name'=> 'ANTOFAGASTA','code' =>'02101','state_code' => '02']);
        City::create(['name'=> 'MEJILLONES','code' =>'02102','state_code' => '02']);
        City::create(['name'=> 'SIERRA GORDA','code' =>'02103','state_code' => '02']);
        City::create(['name'=> 'TALTAL','code' =>'02104','state_code' => '02']);
        City::create(['name'=> 'CALAMA','code' =>'02201','state_code' => '02']);
        City::create(['name'=> 'OLLAGÜE','code' =>'02202','state_code' => '02']);
        City::create(['name'=> 'SAN PEDRO DE ATACAMA','code' =>'02203','state_code' => '02']);
        City::create(['name'=> 'TOCOPILLA','code' =>'02301','state_code' => '02']);
        City::create(['name'=> 'MARÍA ELENA','code' =>'02302','state_code' => '02']);
        City::create(['name'=> 'COPIAPÓ','code' =>'03101','state_code' => '03']);
        City::create(['name'=> 'CALDERA','code' =>'03102','state_code' => '03']);
        City::create(['name'=> 'TIERRA AMARILLA','code' =>'03103','state_code' => '03']);
        City::create(['name'=> 'CHAÑARAL','code' =>'03201','state_code' => '03']);
        City::create(['name'=> 'DIEGO DE ALMAGRO','code' =>'03202','state_code' => '03']);
        City::create(['name'=> 'VALLENAR','code' =>'03301','state_code' => '03']);
        City::create(['name'=> 'ALTO DEL CARMEN','code' =>'03302','state_code' => '03']);
        City::create(['name'=> 'FREIRINA','code' =>'03303','state_code' => '03']);
        City::create(['name'=> 'HUASCO','code' =>'03304','state_code' => '03']);
        City::create(['name'=> 'LA SERENA','code' =>'04101','state_code' => '04']);
        City::create(['name'=> 'COQUIMBO','code' =>'04102','state_code' => '04']);
        City::create(['name'=> 'ANDACOLLO','code' =>'04103','state_code' => '04']);
        City::create(['name'=> 'LA HIGUERA','code' =>'04104','state_code' => '04']);
        City::create(['name'=> 'PAIGUANO','code' =>'04105','state_code' => '04']);
        City::create(['name'=> 'VICUÑA','code' =>'04106','state_code' => '04']);
        City::create(['name'=> 'ILLAPEL','code' =>'04201','state_code' => '04']);
        City::create(['name'=> 'CANELA','code' =>'04202','state_code' => '04']);
        City::create(['name'=> 'LOS VILOS','code' =>'04203','state_code' => '04']);
        City::create(['name'=> 'SALAMANCA','code' =>'04204','state_code' => '04']);
        City::create(['name'=> 'OVALLE','code' =>'04301','state_code' => '04']);
        City::create(['name'=> 'COMBARBALÁ','code' =>'04302','state_code' => '04']);
        City::create(['name'=> 'MONTE PATRIA','code' =>'04303','state_code' => '04']);
        City::create(['name'=> 'PUNITAQUI','code' =>'04304','state_code' => '04']);
        City::create(['name'=> 'RÍO HURTADO','code' =>'04305','state_code' => '04']);
        City::create(['name'=> 'VALPARAÍSO','code' =>'05101','state_code' => '05']);
        City::create(['name'=> 'CASABLANCA','code' =>'05102','state_code' => '05']);
        City::create(['name'=> 'CONCÓN','code' =>'05103','state_code' => '05']);
        City::create(['name'=> 'JUAN FERNÁNDEZ','code' =>'05104','state_code' => '05']);
        City::create(['name'=> 'PUCHUNCAVÍ','code' =>'05105','state_code' => '05']);
        City::create(['name'=> 'QUINTERO','code' =>'05107','state_code' => '05']);
        City::create(['name'=> 'VIÑA DEL MAR','code' =>'05109','state_code' => '05']);
        City::create(['name'=> 'ISLA DE PASCUA','code' =>'05201','state_code' => '05']);
        City::create(['name'=> 'LOS ANDES','code' =>'05301','state_code' => '05']);
        City::create(['name'=> 'CALLE LARGA','code' =>'05302','state_code' => '05']);
        City::create(['name'=> 'RINCONADA','code' =>'05303','state_code' => '05']);
        City::create(['name'=> 'SAN ESTEBAN','code' =>'05304','state_code' => '05']);
        City::create(['name'=> 'LA LIGUA','code' =>'05401','state_code' => '05']);
        City::create(['name'=> 'CABILDO','code' =>'05402','state_code' => '05']);
        City::create(['name'=> 'PAPUDO','code' =>'05403','state_code' => '05']);
        City::create(['name'=> 'PETORCA','code' =>'05404','state_code' => '05']);
        City::create(['name'=> 'ZAPALLAR','code' =>'05405','state_code' => '05']);
        City::create(['name'=> 'QUILLOTA','code' =>'05501','state_code' => '05']);
        City::create(['name'=> 'CALERA','code' =>'05502','state_code' => '05']);
        City::create(['name'=> 'HIJUELAS','code' =>'05503','state_code' => '05']);
        City::create(['name'=> 'LA CRUZ','code' =>'05504','state_code' => '05']);
        City::create(['name'=> 'NOGALES','code' =>'05506','state_code' => '05']);
        City::create(['name'=> 'SAN ANTONIO','code' =>'05601','state_code' => '05']);
        City::create(['name'=> 'ALGARROBO','code' =>'05602','state_code' => '05']);
        City::create(['name'=> 'CARTAGENA','code' =>'05603','state_code' => '05']);
        City::create(['name'=> 'EL QUISCO','code' =>'05604','state_code' => '05']);
        City::create(['name'=> 'EL TABO','code' =>'05605','state_code' => '05']);
        City::create(['name'=> 'SANTO DOMINGO','code' =>'05606','state_code' => '05']);
        City::create(['name'=> 'SAN FELIPE','code' =>'05701','state_code' => '05']);
        City::create(['name'=> 'CATEMU','code' =>'05702','state_code' => '05']);
        City::create(['name'=> 'LLAILLAY','code' =>'05703','state_code' => '05']);
        City::create(['name'=> 'PANQUEHUE','code' =>'05704','state_code' => '05']);
        City::create(['name'=> 'PUTAENDO','code' =>'05705','state_code' => '05']);
        City::create(['name'=> 'SANTA MARÍA','code' =>'05706','state_code' => '05']);
        City::create(['name'=> 'QUILPUÉ','code' =>'05801','state_code' => '05']);
        City::create(['name'=> 'LIMACHE','code' =>'05802','state_code' => '05']);
        City::create(['name'=> 'OLMUÉ','code' =>'05803','state_code' => '05']);
        City::create(['name'=> 'VILLA ALEMANA','code' =>'05804','state_code' => '05']);
        City::create(['name'=> 'RANCAGUA','code' =>'06101','state_code' => '06']);
        City::create(['name'=> 'CODEGUA','code' =>'06102','state_code' => '06']);
        City::create(['name'=> 'COINCO','code' =>'06103','state_code' => '06']);
        City::create(['name'=> 'COLTAUCO','code' =>'06104','state_code' => '06']);
        City::create(['name'=> 'DOÑIHUE','code' =>'06105','state_code' => '06']);
        City::create(['name'=> 'GRANEROS','code' =>'06106','state_code' => '06']);
        City::create(['name'=> 'LAS CABRAS','code' =>'06107','state_code' => '06']);
        City::create(['name'=> 'MACHALÍ','code' =>'06108','state_code' => '06']);
        City::create(['name'=> 'MALLOA','code' =>'06109','state_code' => '06']);
        City::create(['name'=> 'MOSTAZAL','code' =>'06110','state_code' => '06']);
        City::create(['name'=> 'OLIVAR','code' =>'06111','state_code' => '06']);
        City::create(['name'=> 'PEUMO','code' =>'06112','state_code' => '06']);
        City::create(['name'=> 'PICHIDEGUA','code' =>'06113','state_code' => '06']);
        City::create(['name'=> 'QUINTA DE TILCOCO','code' =>'06114','state_code' => '06']);
        City::create(['name'=> 'RENGO','code' =>'06115','state_code' => '06']);
        City::create(['name'=> 'REQUÍNOA','code' =>'06116','state_code' => '06']);
        City::create(['name'=> 'SAN VICENTE','code' =>'06117','state_code' => '06']);
        City::create(['name'=> 'PICHILEMU','code' =>'06201','state_code' => '06']);
        City::create(['name'=> 'LA ESTRELLA','code' =>'06202','state_code' => '06']);
        City::create(['name'=> 'LITUECHE','code' =>'06203','state_code' => '06']);
        City::create(['name'=> 'MARCHIHUE','code' =>'06204','state_code' => '06']);
        City::create(['name'=> 'NAVIDAD','code' =>'06205','state_code' => '06']);
        City::create(['name'=> 'PAREDONES','code' =>'06206','state_code' => '06']);
        City::create(['name'=> 'SAN FERNANDO','code' =>'06301','state_code' => '06']);
        City::create(['name'=> 'CHÉPICA','code' =>'06302','state_code' => '06']);
        City::create(['name'=> 'CHIMBARONGO','code' =>'06303','state_code' => '06']);
        City::create(['name'=> 'LOLOL','code' =>'06304','state_code' => '06']);
        City::create(['name'=> 'NANCAGUA','code' =>'06305','state_code' => '06']);
        City::create(['name'=> 'PALMILLA','code' =>'06306','state_code' => '06']);
        City::create(['name'=> 'PERALILLO','code' =>'06307','state_code' => '06']);
        City::create(['name'=> 'PLACILLA','code' =>'06308','state_code' => '06']);
        City::create(['name'=> 'PUMANQUE','code' =>'06309','state_code' => '06']);
        City::create(['name'=> 'SANTA CRUZ','code' =>'06310','state_code' => '06']);
        City::create(['name'=> 'TALCA','code' =>'07101','state_code' => '07']);
        City::create(['name'=> 'CONSTITUCIÓN','code' =>'07102','state_code' => '07']);
        City::create(['name'=> 'CUREPTO','code' =>'07103','state_code' => '07']);
        City::create(['name'=> 'EMPEDRADO','code' =>'07104','state_code' => '07']);
        City::create(['name'=> 'MAULE','code' =>'07105','state_code' => '07']);
        City::create(['name'=> 'PELARCO','code' =>'07106','state_code' => '07']);
        City::create(['name'=> 'PENCAHUE','code' =>'07107','state_code' => '07']);
        City::create(['name'=> 'RÍO CLARO','code' =>'07108','state_code' => '07']);
        City::create(['name'=> 'SAN CLEMENTE','code' =>'07109','state_code' => '07']);
        City::create(['name'=> 'SAN RAFAEL','code' =>'07110','state_code' => '07']);
        City::create(['name'=> 'CAUQUENES','code' =>'07201','state_code' => '07']);
        City::create(['name'=> 'CHANCO','code' =>'07202','state_code' => '07']);
        City::create(['name'=> 'PELLUHUE','code' =>'07203','state_code' => '07']);
        City::create(['name'=> 'CURICÓ','code' =>'07301','state_code' => '07']);
        City::create(['name'=> 'HUALAÑÉ','code' =>'07302','state_code' => '07']);
        City::create(['name'=> 'LICANTÉN','code' =>'07303','state_code' => '07']);
        City::create(['name'=> 'MOLINA','code' =>'07304','state_code' => '07']);
        City::create(['name'=> 'RAUCO','code' =>'07305','state_code' => '07']);
        City::create(['name'=> 'ROMERAL','code' =>'07306','state_code' => '07']);
        City::create(['name'=> 'SAGRADA FAMILIA','code' =>'07307','state_code' => '07']);
        City::create(['name'=> 'TENO','code' =>'07308','state_code' => '07']);
        City::create(['name'=> 'VICHUQUÉN','code' =>'07309','state_code' => '07']);
        City::create(['name'=> 'LINARES','code' =>'07401','state_code' => '07']);
        City::create(['name'=> 'COLBÚN','code' =>'07402','state_code' => '07']);
        City::create(['name'=> 'LONGAVÍ','code' =>'07403','state_code' => '07']);
        City::create(['name'=> 'PARRAL','code' =>'07404','state_code' => '07']);
        City::create(['name'=> 'RETIRO','code' =>'07405','state_code' => '07']);
        City::create(['name'=> 'SAN JAVIER','code' =>'07406','state_code' => '07']);
        City::create(['name'=> 'VILLA ALEGRE','code' =>'07407','state_code' => '07']);
        City::create(['name'=> 'YERBAS BUENAS','code' =>'07408','state_code' => '07']);
        City::create(['name'=> 'CONCEPCIÓN','code' =>'08101','state_code' => '08']);
        City::create(['name'=> 'CORONEL','code' =>'08102','state_code' => '08']);
        City::create(['name'=> 'CHIGUAYANTE','code' =>'08103','state_code' => '08']);
        City::create(['name'=> 'FLORIDA','code' =>'08104','state_code' => '08']);
        City::create(['name'=> 'HUALQUI','code' =>'08105','state_code' => '08']);
        City::create(['name'=> 'LOTA','code' =>'08106','state_code' => '08']);
        City::create(['name'=> 'PENCO','code' =>'08107','state_code' => '08']);
        City::create(['name'=> 'SAN PEDRO DE LA PAZ','code' =>'08108','state_code' => '08']);
        City::create(['name'=> 'SANTA JUANA','code' =>'08109','state_code' => '08']);
        City::create(['name'=> 'TALCAHUANO','code' =>'08110','state_code' => '08']);
        City::create(['name'=> 'TOMÉ','code' =>'08111','state_code' => '08']);
        City::create(['name'=> 'HUALPÉN','code' =>'08112','state_code' => '08']);
        City::create(['name'=> 'LEBU','code' =>'08201','state_code' => '08']);
        City::create(['name'=> 'ARAUCO','code' =>'08202','state_code' => '08']);
        City::create(['name'=> 'CAÑETE','code' =>'08203','state_code' => '08']);
        City::create(['name'=> 'CONTULMO','code' =>'08204','state_code' => '08']);
        City::create(['name'=> 'CURANILAHUE','code' =>'08205','state_code' => '08']);
        City::create(['name'=> 'LOS ÁLAMOS','code' =>'08206','state_code' => '08']);
        City::create(['name'=> 'TIRÚA','code' =>'08207','state_code' => '08']);
        City::create(['name'=> 'LOS ÁNGELES','code' =>'08301','state_code' => '08']);
        City::create(['name'=> 'ANTUCO','code' =>'08302','state_code' => '08']);
        City::create(['name'=> 'CABRERO','code' =>'08303','state_code' => '08']);
        City::create(['name'=> 'LAJA','code' =>'08304','state_code' => '08']);
        City::create(['name'=> 'MULCHÉN','code' =>'08305','state_code' => '08']);
        City::create(['name'=> 'NACIMIENTO','code' =>'08306','state_code' => '08']);
        City::create(['name'=> 'NEGRETE','code' =>'08307','state_code' => '08']);
        City::create(['name'=> 'QUILACO','code' =>'08308','state_code' => '08']);
        City::create(['name'=> 'QUILLECO','code' =>'08309','state_code' => '08']);
        City::create(['name'=> 'SAN ROSENDO','code' =>'08310','state_code' => '08']);
        City::create(['name'=> 'SANTA BÁRBARA','code' =>'08311','state_code' => '08']);
        City::create(['name'=> 'TUCAPEL','code' =>'08312','state_code' => '08']);
        City::create(['name'=> 'YUMBEL','code' =>'08313','state_code' => '08']);
        City::create(['name'=> 'ALTO BIOBÍO','code' =>'08314','state_code' => '08']);
        City::create(['name'=> 'CHILLÁN','code' =>'08401','state_code' => '08']);
        City::create(['name'=> 'BULNES','code' =>'08402','state_code' => '08']);
        City::create(['name'=> 'COBQUECURA','code' =>'08403','state_code' => '08']);
        City::create(['name'=> 'COELEMU','code' =>'08404','state_code' => '08']);
        City::create(['name'=> 'COIHUECO','code' =>'08405','state_code' => '08']);
        City::create(['name'=> 'CHILLÁN VIEJO','code' =>'08406','state_code' => '08']);
        City::create(['name'=> 'EL CARMEN','code' =>'08407','state_code' => '08']);
        City::create(['name'=> 'NINHUE','code' =>'08408','state_code' => '08']);
        City::create(['name'=> 'ÑIQUÉN','code' =>'08409','state_code' => '08']);
        City::create(['name'=> 'PEMUCO','code' =>'08410','state_code' => '08']);
        City::create(['name'=> 'PINTO','code' =>'08411','state_code' => '08']);
        City::create(['name'=> 'PORTEZUELO','code' =>'08412','state_code' => '08']);
        City::create(['name'=> 'QUILLÓN','code' =>'08413','state_code' => '08']);
        City::create(['name'=> 'QUIRIHUE','code' =>'08414','state_code' => '08']);
        City::create(['name'=> 'RÁNQUIL','code' =>'08415','state_code' => '08']);
        City::create(['name'=> 'SAN CARLOS','code' =>'08416','state_code' => '08']);
        City::create(['name'=> 'SAN FABIÁN','code' =>'08417','state_code' => '08']);
        City::create(['name'=> 'SAN IGNACIO','code' =>'08418','state_code' => '08']);
        City::create(['name'=> 'SAN NICOLÁS','code' =>'08419','state_code' => '08']);
        City::create(['name'=> 'TREGUACO','code' =>'08420','state_code' => '08']);
        City::create(['name'=> 'YUNGAY','code' =>'08421','state_code' => '08']);
        City::create(['name'=> 'TEMUCO','code' =>'09101','state_code' => '09']);
        City::create(['name'=> 'CARAHUE','code' =>'09102','state_code' => '09']);
        City::create(['name'=> 'CUNCO','code' =>'09103','state_code' => '09']);
        City::create(['name'=> 'CURARREHUE','code' =>'09104','state_code' => '09']);
        City::create(['name'=> 'FREIRE','code' =>'09105','state_code' => '09']);
        City::create(['name'=> 'GALVARINO','code' =>'09106','state_code' => '09']);
        City::create(['name'=> 'GORBEA','code' =>'09107','state_code' => '09']);
        City::create(['name'=> 'LAUTARO','code' =>'09108','state_code' => '09']);
        City::create(['name'=> 'LONCOCHE','code' =>'09109','state_code' => '09']);
        City::create(['name'=> 'MELIPEUCO','code' =>'09110','state_code' => '09']);
        City::create(['name'=> 'NUEVA IMPERIAL','code' =>'09111','state_code' => '09']);
        City::create(['name'=> 'PADRE LAS CASAS','code' =>'09112','state_code' => '09']);
        City::create(['name'=> 'PERQUENCO','code' =>'09113','state_code' => '09']);
        City::create(['name'=> 'PITRUFQUÉN','code' =>'09114','state_code' => '09']);
        City::create(['name'=> 'PUCÓN','code' =>'09115','state_code' => '09']);
        City::create(['name'=> 'SAAVEDRA','code' =>'09116','state_code' => '09']);
        City::create(['name'=> 'TEODORO SCHMIDT','code' =>'09117','state_code' => '09']);
        City::create(['name'=> 'TOLTÉN','code' =>'09118','state_code' => '09']);
        City::create(['name'=> 'VILCÚN','code' =>'09119','state_code' => '09']);
        City::create(['name'=> 'VILLARRICA','code' =>'09120','state_code' => '09']);
        City::create(['name'=> 'CHOLCHOL','code' =>'09121','state_code' => '09']);
        City::create(['name'=> 'ANGOL','code' =>'09201','state_code' => '09']);
        City::create(['name'=> 'COLLIPULLI','code' =>'09202','state_code' => '09']);
        City::create(['name'=> 'CURACAUTÍN','code' =>'09203','state_code' => '09']);
        City::create(['name'=> 'ERCILLA','code' =>'09204','state_code' => '09']);
        City::create(['name'=> 'LONQUIMAY','code' =>'09205','state_code' => '09']);
        City::create(['name'=> 'LOS SAUCES','code' =>'09206','state_code' => '09']);
        City::create(['name'=> 'LUMACO','code' =>'09207','state_code' => '09']);
        City::create(['name'=> 'PURÉN','code' =>'09208','state_code' => '09']);
        City::create(['name'=> 'RENAICO','code' =>'09209','state_code' => '09']);
        City::create(['name'=> 'TRAIGUÉN','code' =>'09210','state_code' => '09']);
        City::create(['name'=> 'VICTORIA','code' =>'09211','state_code' => '09']);
        City::create(['name'=> 'VALDIVIA','code' =>'14101','state_code' => '14']);
        City::create(['name'=> 'CORRAL','code' =>'14102','state_code' => '14']);
        City::create(['name'=> 'LANCO','code' =>'14103','state_code' => '14']);
        City::create(['name'=> 'LOS LAGOS','code' =>'14104','state_code' => '14']);
        City::create(['name'=> 'MÁFIL','code' =>'14105','state_code' => '14']);
        City::create(['name'=> 'MARIQUINA','code' =>'14106','state_code' => '14']);
        City::create(['name'=> 'PAILLACO','code' =>'14107','state_code' => '14']);
        City::create(['name'=> 'PANGUIPULLI','code' =>'14108','state_code' => '14']);
        City::create(['name'=> 'LA UNIÓN','code' =>'14201','state_code' => '14']);
        City::create(['name'=> 'FUTRONO','code' =>'14202','state_code' => '14']);
        City::create(['name'=> 'LAGO RANCO','code' =>'14203','state_code' => '14']);
        City::create(['name'=> 'RÍO BUENO','code' =>'14204','state_code' => '14']);
        City::create(['name'=> 'PUERTO MONTT','code' =>'10101','state_code' => '10']);
        City::create(['name'=> 'CALBUCO','code' =>'10102','state_code' => '10']);
        City::create(['name'=> 'COCHAMÓ','code' =>'10103','state_code' => '10']);
        City::create(['name'=> 'FRESIA','code' =>'10104','state_code' => '10']);
        City::create(['name'=> 'FRUTILLAR','code' =>'10105','state_code' => '10']);
        City::create(['name'=> 'LOS MUERMOS','code' =>'10106','state_code' => '10']);
        City::create(['name'=> 'LLANQUIHUE','code' =>'10107','state_code' => '10']);
        City::create(['name'=> 'MAULLÍN','code' =>'10108','state_code' => '10']);
        City::create(['name'=> 'PUERTO VARAS','code' =>'10109','state_code' => '10']);
        City::create(['name'=> 'CASTRO','code' =>'10201','state_code' => '10']);
        City::create(['name'=> 'ANCUD','code' =>'10202','state_code' => '10']);
        City::create(['name'=> 'CHONCHI','code' =>'10203','state_code' => '10']);
        City::create(['name'=> 'CURACO DE VÉLEZ','code' =>'10204','state_code' => '10']);
        City::create(['name'=> 'DALCAHUE','code' =>'10205','state_code' => '10']);
        City::create(['name'=> 'PUQUELDÓN','code' =>'10206','state_code' => '10']);
        City::create(['name'=> 'QUEILÉN','code' =>'10207','state_code' => '10']);
        City::create(['name'=> 'QUELLÓN','code' =>'10208','state_code' => '10']);
        City::create(['name'=> 'QUEMCHI','code' =>'10209','state_code' => '10']);
        City::create(['name'=> 'QUINCHAO','code' =>'10210','state_code' => '10']);
        City::create(['name'=> 'OSORNO','code' =>'10301','state_code' => '10']);
        City::create(['name'=> 'PUERTO OCTAY','code' =>'10302','state_code' => '10']);
        City::create(['name'=> 'PURRANQUE','code' =>'10303','state_code' => '10']);
        City::create(['name'=> 'PUYEHUE','code' =>'10304','state_code' => '10']);
        City::create(['name'=> 'RÍO NEGRO','code' =>'10305','state_code' => '10']);
        City::create(['name'=> 'SAN JUAN DE LA COSTA','code' =>'10306','state_code' => '10']);
        City::create(['name'=> 'SAN PABLO','code' =>'10307','state_code' => '10']);
        City::create(['name'=> 'CHAITÉN','code' =>'10401','state_code' => '10']);
        City::create(['name'=> 'FUTALEUFÚ','code' =>'10402','state_code' => '10']);
        City::create(['name'=> 'HUALAIHUÉ','code' =>'10403','state_code' => '10']);
        City::create(['name'=> 'PALENA','code' =>'10404','state_code' => '10']);
        City::create(['name'=> 'COIHAIQUE','code' =>'11101','state_code' => '11']);
        City::create(['name'=> 'LAGO VERDE','code' =>'11102','state_code' => '11']);
        City::create(['name'=> 'AISÉN','code' =>'11201','state_code' => '11']);
        City::create(['name'=> 'CISNES','code' =>'11202','state_code' => '11']);
        City::create(['name'=> 'GUAITECAS','code' =>'11203','state_code' => '11']);
        City::create(['name'=> 'COCHRANE','code' =>'11301','state_code' => '11']);
        City::create(['name'=> 'O’HIGGINS','code' =>'11302','state_code' => '11']);
        City::create(['name'=> 'TORTEL','code' =>'11303','state_code' => '11']);
        City::create(['name'=> 'CHILE CHICO','code' =>'11401','state_code' => '11']);
        City::create(['name'=> 'RÍO IBÁÑEZ','code' =>'11402','state_code' => '11']);
        City::create(['name'=> 'PUNTA ARENAS','code' =>'12101','state_code' => '12']);
        City::create(['name'=> 'LAGUNA BLANCA','code' =>'12102','state_code' => '12']);
        City::create(['name'=> 'RÍO VERDE','code' =>'12103','state_code' => '12']);
        City::create(['name'=> 'SAN GREGORIO','code' =>'12104','state_code' => '12']);
        City::create(['name'=> 'CABO DE HORNOS','code' =>'12201','state_code' => '12']);
        City::create(['name'=> 'ANTÁRTICA','code' =>'12202','state_code' => '12']);
        City::create(['name'=> 'PORVENIR','code' =>'12301','state_code' => '12']);
        City::create(['name'=> 'PRIMAVERA','code' =>'12302','state_code' => '12']);
        City::create(['name'=> 'TIMAUKEL','code' =>'12303','state_code' => '12']);
        City::create(['name'=> 'NATALES','code' =>'12401','state_code' => '12']);
        City::create(['name'=> 'TORRES DEL PAINE','code' =>'12402','state_code' => '12']);
        City::create(['name'=> 'SANTIAGO','code' =>'13101','state_code' => '13']);
        City::create(['name'=> 'CERRILLOS','code' =>'13102','state_code' => '13']);
        City::create(['name'=> 'CERRO NAVIA','code' =>'13103','state_code' => '13']);
        City::create(['name'=> 'CONCHALÍ','code' =>'13104','state_code' => '13']);
        City::create(['name'=> 'EL BOSQUE','code' =>'13105','state_code' => '13']);
        City::create(['name'=> 'ESTACIÓN CENTRAL','code' =>'13106','state_code' => '13']);
        City::create(['name'=> 'HUECHURABA','code' =>'13107','state_code' => '13']);
        City::create(['name'=> 'INDEPENDENCIA','code' =>'13108','state_code' => '13']);
        City::create(['name'=> 'LA CISTERNA','code' =>'13109','state_code' => '13']);
        City::create(['name'=> 'LA FLORIDA','code' =>'13110','state_code' => '13']);
        City::create(['name'=> 'LA GRANJA','code' =>'13111','state_code' => '13']);
        City::create(['name'=> 'LA PINTANA','code' =>'13112','state_code' => '13']);
        City::create(['name'=> 'LA REINA','code' =>'13113','state_code' => '13']);
        City::create(['name'=> 'LAS CONDES','code' =>'13114','state_code' => '13']);
        City::create(['name'=> 'LO BARNECHEA','code' =>'13115','state_code' => '13']);
        City::create(['name'=> 'LO ESPEJO','code' =>'13116','state_code' => '13']);
        City::create(['name'=> 'LO PRADO','code' =>'13117','state_code' => '13']);
        City::create(['name'=> 'MACUL','code' =>'13118','state_code' => '13']);
        City::create(['name'=> 'MAIPÚ','code' =>'13119','state_code' => '13']);
        City::create(['name'=> 'ÑUÑOA','code' =>'13120','state_code' => '13']);
        City::create(['name'=> 'PEDRO AGUIRRE CERDA','code' =>'13121','state_code' => '13']);
        City::create(['name'=> 'PEÑALOLÉN','code' =>'13122','state_code' => '13']);
        City::create(['name'=> 'PROVIDENCIA','code' =>'13123','state_code' => '13']);
        City::create(['name'=> 'PUDAHUEL','code' =>'13124','state_code' => '13']);
        City::create(['name'=> 'QUILICURA','code' =>'13125','state_code' => '13']);
        City::create(['name'=> 'QUINTA NORMAL','code' =>'13126','state_code' => '13']);
        City::create(['name'=> 'RECOLETA','code' =>'13127','state_code' => '13']);
        City::create(['name'=> 'RENCA','code' =>'13128','state_code' => '13']);
        City::create(['name'=> 'SAN JOAQUÍN','code' =>'13129','state_code' => '13']);
        City::create(['name'=> 'SAN MIGUEL','code' =>'13130','state_code' => '13']);
        City::create(['name'=> 'SAN RAMÓN','code' =>'13131','state_code' => '13']);
        City::create(['name'=> 'VITACURA','code' =>'13132','state_code' => '13']);
        City::create(['name'=> 'PUENTE ALTO','code' =>'13201','state_code' => '13']);
        City::create(['name'=> 'PIRQUE','code' =>'13202','state_code' => '13']);
        City::create(['name'=> 'SAN JOSÉ DE MAIPO','code' =>'13203','state_code' => '13']);
        City::create(['name'=> 'COLINA','code' =>'13301','state_code' => '13']);
        City::create(['name'=> 'LAMPA','code' =>'13302','state_code' => '13']);
        City::create(['name'=> 'TILTIL','code' =>'13303','state_code' => '13']);
        City::create(['name'=> 'SAN BERNARDO','code' =>'13401','state_code' => '13']);
        City::create(['name'=> 'BUIN','code' =>'13402','state_code' => '13']);
        City::create(['name'=> 'CALERA DE TANGO','code' =>'13403','state_code' => '13']);
        City::create(['name'=> 'PAINE','code' =>'13404','state_code' => '13']);
        City::create(['name'=> 'MELIPILLA','code' =>'13501','state_code' => '13']);
        City::create(['name'=> 'ALHUÉ','code' =>'13502','state_code' => '13']);
        City::create(['name'=> 'CURACAVÍ','code' =>'13503','state_code' => '13']);
        City::create(['name'=> 'MARÍA PINTO','code' =>'13504','state_code' => '13']);
        City::create(['name'=> 'SAN PEDRO','code' =>'13505','state_code' => '13']);
        City::create(['name'=> 'TALAGANTE','code' =>'13601','state_code' => '13']);
        City::create(['name'=> 'EL MONTE','code' =>'13602','state_code' => '13']);
        City::create(['name'=> 'ISLA DE MAIPO','code' =>'13603','state_code' => '13']);
        City::create(['name'=> 'PADRE HURTADO','code' =>'13604','state_code' => '13']);
        City::create(['name'=> 'PEÑAFLOR','code' =>'13605','state_code' => '13']);
    }
}
